---@class DyPalette
---
--- Backgrounds
---@field bg            string  Main editor background
---@field bg_surface    string  Panels, sidebars, inactive splits
---@field bg_highlight  string  Line highlight, current item
---@field bg_floating   string  Tooltips, popup menus, dropdowns
---@field bg_inactive   string  Unfocused titlebar/winbar background
---@field bg_statusline string  Statusline/winbar background
---@field bg_cursorline string  Cursor line, subtler than bg_highlight
---@field bg_panel      string  Focused panel/pane header background
---@field bg_selection     string  Text selection background
---@field bg_visual        string  Visual mode / range selection background
---@field bg_shadow        string  Drop shadow for floating elements
---
--- Text
--- Normal text
---@field fg string canonical shorthand — always equal to on_bg
---@field on_bg string explicit form for template generators
---@field on_surface string panels, sidebars, neo-tree
---@field on_highlight string line highlight, current item row
---@field on_floating string tooltips, popup menus, documentation
---@field on_selection string text within a selection range
---@field on_visual string text within a visual mode selection
---@field on_cursor string text under the cursor block
---@field on_statusline string statusline / winbar text
--- Normal text on accent / status backgrounds
---@field on_primary string badge labels, button text on primary bg
---@field on_secondary string badge labels on secondary bg
---@field on_error string text on error-colored surfaces
---@field on_warning string text on warning-colored surfaces
---@field on_info string text on info-colored surfaces
---@field on_success string text on success-colored surfaces
--- Muted text
---@field muted_on_bg string comments, secondary labels in the editor
---@field muted_on_surface string dim filenames, git status in panels
---@field muted_on_floating string secondary text in tooltips and docs
---@field muted_on_statusline string inactive mode segment, file encoding
--- Disabled text
---@field disabled_on_bg string placeholder text, unavailable keymaps
---@field disabled_on_surface string greyed-out items in file trees and menus
---@field disabled_on_floating string greyed-out items in floating windows (Snacks' Picker)
--- Decorative non-text
---@field nontext_on_bg string indent guides, ~ markers, virtual decorations
--- Text on ANSI colors
---@field on_ansi_black string  text on black (ansi 0)
---@field on_ansi_red string  text on red (ansi 1)
---@field on_ansi_green string  text on green (ansi 2)
---@field on_ansi_yellow string  text on yellow (ansi 3)
---@field on_ansi_blue string  text on blue (ansi 4)
---@field on_ansi_magenta string  text on magenta (ansi 5)
---@field on_ansi_cyan string  text on cyan (ansi 6)
---@field on_ansi_white string  text on white (ansi 7)
---@field on_ansi_bright_black string text on bright black (ansi 8)
---@field on_ansi_bright_red string text on bright red (ansi 9)
---@field on_ansi_bright_green string text on bright green (ansi 10)
---@field on_ansi_bright_yellow string text on bright yellow (ansi 11)
---@field on_ansi_bright_blue string text on bright blue (ansi 12)
---@field on_ansi_bright_magenta string text on bright magenta (ansi 13)
---@field on_ansi_bright_cyan string text on bright cyan (ansi 14)
---@field on_ansi_bright_white string text on bright white (ansi 15)
---
--- Interactive
---@field cursor        string  Cursor block/bar/underline color
---@field prompt        string  Input prompt / command line foreground
---@field fg_match      string  Matched characters in fuzzy search results
---@field mark          string  Explicitly marked items (yazi, ranger)
---@field url           string  Hyperlinks and navigable URLs
---
--- Search
---@field bg_search     string  Current/active search match background
---@field bg_match      string  All other search match backgrounds
---
--- Diff
---@field diff_add      string  Added line background
---@field diff_delete   string  Deleted line background
---@field diff_change   string  Changed line background
---@field diff_text     string  Changed text within a changed line
---
--- Structure
---@field border        string  Default border and separator
---@field border_active string  Focused/active border
---@field indicator     string  Split direction indicator, mode cue
---
--- Accents
---@field primary       string  Main interactive color (focused borders, active elements)
---@field secondary     string  Supporting accent color
---
--- Diagnostics
---@field error         string  Errors and failures
---@field warning       string  Warnings and caution
---@field info          string  Informational messages
---@field hint          string  LSP hints, subtle suggestions
---@field success       string  Success and passing state
---
--- Syntax
---@field syntax_variable   string  Variables, tags (base08)
---@field syntax_constant   string  Integers, booleans, constants (base09)
---@field syntax_type       string  Classes, types (base0A)
---@field syntax_string     string  Strings (base0B)
---@field syntax_escape     string  Regex, escape chars, embedded (base0C)
---@field syntax_function   string  Functions, methods, headings (base0D)
---@field syntax_keyword    string  Keywords, storage, selectors (base0E)
---@field syntax_deprecated string  Deprecated, opening/closing tags (base0F)
---@field syntax_comment    string  Comments (base03)
---@field syntax_punctuation string Punctuation, operators (base04)
---
--- ANSI terminal palette (colors 0–15)
--- Matches vim.g.terminal_color_N — consumed by toggleterm, floaterm, etc.
---@field terminal_color_0  string  Normal black   (ansi 0)
---@field terminal_color_1  string  Normal red     (ansi 1)
---@field terminal_color_2  string  Normal green   (ansi 2)
---@field terminal_color_3  string  Normal yellow  (ansi 3)
---@field terminal_color_4  string  Normal blue    (ansi 4)
---@field terminal_color_5  string  Normal magenta (ansi 5)
---@field terminal_color_6  string  Normal cyan    (ansi 6)
---@field terminal_color_7  string  Normal white   (ansi 7)
---@field terminal_color_8  string  Bright black   (ansi 8)
---@field terminal_color_9  string  Bright red     (ansi 9)
---@field terminal_color_10 string  Bright green   (ansi 10)
---@field terminal_color_11 string  Bright yellow  (ansi 11)
---@field terminal_color_12 string  Bright blue    (ansi 12)
---@field terminal_color_13 string  Bright magenta (ansi 13)
---@field terminal_color_14 string  Bright cyan    (ansi 14)
---@field terminal_color_15 string  Bright white   (ansi 15)
---
--- Copy of the above but more useful for humans (me)
---@field ansi_black string  Normal black   (ansi 0)
---@field ansi_red string  Normal red     (ansi 1)
---@field ansi_green string  Normal green   (ansi 2)
---@field ansi_yellow string  Normal yellow  (ansi 3)
---@field ansi_blue string  Normal blue    (ansi 4)
---@field ansi_magenta string  Normal magenta (ansi 5)
---@field ansi_cyan string  Normal cyan    (ansi 6)
---@field ansi_white string  Normal white   (ansi 7)
---@field ansi_bright_black string  Bright black   (ansi 8)
---@field ansi_bright_red string  Bright red     (ansi 9)
---@field ansi_bright_green string  Bright green   (ansi 10)
---@field ansi_bright_yellow string  Bright yellow  (ansi 11)
---@field ansi_bright_blue string  Bright blue    (ansi 12)
---@field ansi_bright_magenta string  Bright magenta (ansi 13)
---@field ansi_bright_cyan string  Bright cyan    (ansi 14)
---@field ansi_bright_white string  Bright white   (ansi 15)

---@class DyHex
---@field __chroma__ string   Always "Hex"
---@field r          integer  Red channel 0–255
---@field g          integer  Green channel 0–255
---@field b          integer  Blue channel 0–255
---@field a          number   Alpha 0.0–1.0

---@alias DyUIColors table<string, DyHex>
